api_user_register:
  path: /api/user/register/{token}/
  defaults: { _controller: UserBundle:User:api_register}
  methods: POST
api_user_login:
  path: /api/user/login/{username}/{password}/{token}/
  defaults: { _controller: UserBundle:User:api_login}
  methods: GET
user_user_index:
  path: /users/index.html
  defaults: { _controller: UserBundle:User:index}
user_user_edit:
  path: /users/edit/{id}.html
  defaults: { _controller: UserBundle:User:edit}
  requirements:
      id:  \d+ 
api_user_change_password:
  path: /api/user/password/{id}/{password}/{new_password}/{token}/
  defaults: { _controller: UserBundle:User:api_change_password}
  methods: GET
api_user_edit_name:
  path: /api/user/name/{id}/{name}/{key}/{token}/
  defaults: { _controller: UserBundle:User:api_edit_name}
  methods: GET
api_user_email:
  path: /api/user/email/{email}/{token}/
  defaults: { _controller: UserBundle:Resetting:api_email}
  methods: GET
api_user_request:
  path: /api/user/request/{key}/{token}/
  defaults: { _controller: UserBundle:Resetting:api_request}
  methods: GET
api_user_reset:
  path: /api/user/reset/{id}/{key}/{new_password}/{token}/
  defaults: { _controller: UserBundle:Resetting:api_reset}
  methods: GET
api_user_check:
  path: /api/user/check/{id}/{key}/{token}/
  defaults: { _controller: UserBundle:User:api_check}
  methods: GET
